### ISSUE TITLE
Add an integration test

### ISSUE THREAD

**Issue by psiinon** [zaproxy/browser-extension#19]
We have some unit tests, but no way of automatically checking that the extension actually runs in the browser.
So we need at least one test which starts each browser and verifies the extension loads. Note that Chrome will currently fail 😉 
How to verify the extension loads? Er, not sure right now - maybe some other open source browser extensions do this?
Ideally we will extend the integration tests to test the actual extension.
This could be done by:

1. Creating a simple test website which has a page with the feature to test (eg a link)
2. Starting a 'fake' ZAP server - ie a webserver where we can check the requests to it
3. Starting the relevant browser with the extension loaded and point it at the test page
4. Verifying the fake ZAP server gets the expected data from the extension

So non trivial, but once we have this framework we'll be able to test all of the extension functionality which will be _really_ helpful

This issue doesnt have to do all of that, this is just indicating the direction I'd like us to go in

**Comment by aryangupta701** [comment]
This can be closed now @psiinon.
