### ISSUE TITLE
Browser crashing

### ISSUE THREAD

**Issue by karthikuj** [zaproxy/browser-extension#46]
The browser sometimes hangs indefinitely and sometimes crashes when I open a website with a lot of DOM activity.

Steps to reproduce:
1. Build the extension.
2. Load it in the browser, I tested this on chrome version 113.0.5672.126.
3. Enter your ZAP proxy address and API key in the extension.
4. Open https://getastra.com/

This should hang or crash the browser.

**Comment by aryangupta701** [comment]
Earlier I thought this issue is due to the animations present in the website but for this website which donot have any animations also it hangs the browser : https://www.w3schools.com/html/html_iframe.asp. 

Steps to reproduce is similar to the above written steps.

**Comment by psiinon** [comment]
I've tested it with https://getastra.com/ left the browser running for a bit and then killed it.
ZAP received over 30,000 nodeAdded events!
The vast majority are links and we seem to keep getting events for the same nodes being 'added'.
We received over 200 for just one specific link :/
Clearly we need to handle this better, but it would also be good to know why so many nodeAdded events are getting generated by the browser.
Anyone know?

**Comment by aryangupta701** [comment]
this has something to do with 'subtree' will need to dig deeper into what subtree flag do

**Comment by aryangupta701** [comment]
oh got it.
